# Generated by Django 4.2.1 on 2023-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
    ]
