# Generated by Django 4.2.1 on 2023-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feedback_coffee_is_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': 'Coffee', 'verbose_name_plural': 'Coffee lar'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
