# Generated by Django 4.2 on 2023-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_coffee_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
